service: aidannairn--server
provider:
  name: aws
  runtime: nodejs14.x
  stage: prod
  region: us-east-1
  memorySize: 128
functions:
  app:
    handler: app/app.handler
    events: 
      - http: 
          path: /
          method: ANY
          cors: 
            origin: ''
            headers:
              - Accept
              - Content-Type
              - Authorization
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amz-Trace-Id
              - Set-Cookie
            allowCredentials: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors:
            origin: ''
            headers:
              - Accept
              - Content-Type
              - Authorization
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amz-Trace-Id
              - Set-Cookie
            allowCredentials: true